### ISSUE TITLE
Thunno Corpus

### ISSUE THREAD

**Issue by jfioasd** [Thunno/Thunno#2]
Similar to [this](https://github.com/DennisMitchell/jellylanguage/issues/91) issue, I did an analysis on Thunno programs. [Query used.](https://data.stackexchange.com/codegolf/query/edit/1725442) Code to analyze the data is same as the linked issue. Results:
```
2-graphs:
  24 1+
  15 sA
  13 z0
  10 Au
   9 +s
   8 34
   8 s+
   8 10
   8 z1
   8 AI
   8 R1
   8 ZZ
   7 Ah
   7 DZ
   7 ZU
   6 4C
   6 xs
   6 D1
   6 sZ
   6 ZK
   6 gA
   6 0s
   6 AK
   6 "A
   5 "D
   5 z[
   5 z(
   5 ZA
   5 AJ
   5 22

3-graphs:
   7 R1+
   6 34C
   6 s+s
   6 0sA
   5 z0s
   5 sAI
   4 "D3
   4 D34
   4 4CX
   4 CXx
   4 Xx+
   4 x+x
   4 +xs
   4 xs+
   4 +s+
   4 sAh
   4 1+:
   4 sAq
   4 eAu
   4 ZZz
   3 10@
   3 e1+
   3 +z0
   3 z0A
   3 gAu
   3 1=k
   3 RZw
   3 .AK
   3 212
   3 1+Z

4-graphs:
   5 z0sA
   4 "D34
   4 D34C
   4 34CX
   4 4CXx
   4 CXx+
   4 Xx+x
   4 x+xs
   4 +xs+
   4 xs+s
   4 s+s+
   3 0sAI
   2 :gNk
   2 sAh1
   2 Ah1+
   2 1+:g
   2 1+z0
   2 +z0A
   2 sAIS
   2 gAzs
   2 AzsA
   2 zsAq
   2 sAqk
   2 0sAh
   2 2122
   2 2212
   2 EeAu
   2 Au3*
   2 *ESz
   2 2RZw
```

### 2-graphs:
Since there are so many 2-byte operations, it's hard to judge simply from the 2-graph results.

* `1+`: definitely worth making a 1-byte command.
* `z0` and `z1`: commands for taking input definitely needs to be shorter. These can appear really frequently
* `34C` is common: you can add a command for pushing a quote.
* `Au` (dumping the stack) is pretty useful as a 1-byte command.
* `10`: this is often a 1-byte command in many golfing languages.
* `AI`: nice to have indexing as 1 byte.
* `ZZ`: zipping is a good operation to have as 1 byte as well.

**Comment by nayakrujul** [comment]
Thanks so much for doing this, and also thanks for the suggestions, but I'm a bit hesitant to change stuff in Thunno (backwards compatability and all that). Also, I'm currently working on Thunno 2. However, I can inform you that in Thunno 2 (still a work in progress), increment/decrement, inputs, literals for 10, 16, and 256, dumping to the stack, indexing (1-based and 0-based), and zip are all 1-byte commands. If you've got any more remarks, I can update you on how many bytes that command is in Thunno 2.
